server:
  port: ${PORT:8080}

spring:
  application:
    name: openapi-codegen
  output:
    ansi:
      enabled: always
  main:
    banner-mode: "off"
  # Disables spring security basic auth
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

# Springfox swagger definition path
springfox:
  documentation:
    swagger:
      v2:
        path: /v2/api-docs/swagger.json

# Logging level configuration
logging:
  level:
    root: INFO
    com.github.pwnmn: DEBUG

# Feign configuration
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: full

# Feign client base URLs
pet:
  url: https://petstore3.swagger.io/api/v3
store:
  url: https://petstore3.swagger.io/api/v3
user:
  url: https://petstore3.swagger.io/api/v3